name: chatapp
description: A new Flutter project.

publish_to: 'none' 

version: 6.0.13

environment:
  sdk: '>=2.18.6 <3.0.0'

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0 #屏幕适配 https://pub.dev/packages/flutter_screenutil
  permission_handler: ^10.2.0 #权限申请 https://pub.dev/packages/permission_handler
  get: ^4.6.5 #路由管理 https://pub.dev/packages/get
  photo_view: ^0.14.0 #图片浏览器 https://pub.dev/packages/photo_view
  image_gallery_saver: ^1.7.1 #图片保存 https://pub.dev/packages/image_gallery_saver
  flutter_easyloading: ^3.0.5 #悬浮提示 https://pub.dev/packages/flutter_easyloading
  animated_floating_buttons: ^0.0.1 #悬浮按钮 https://pub.dev/packages/animated_floating_buttons
  spring_button: ^2.0.0 #弹跳按钮 https://pub.dev/packages/spring_button
  keframe: ^3.0.0 #加载优化 https://pub.dev/packages/keframe
  cool_dropdown: ^1.4.2 #下拉框 https://pub.dev/packages/cool_dropdown
  package_info_plus: ^3.0.2 #查询应用信息 https://pub.dev/packages/package_info_plus
  shared_preferences: ^2.0.17 #数据存储 https://pub.dev/packages/shared_preferences
  image_picker: ^0.8.6+1 #图片选项 https://pub.dev/packages/image_picker
  just_audio: ^0.9.31 #音频播放 https://pub.dev/packages/just_audio
  # flutter_launcher_icons: ^0.11.0 #生成应用图标 https://pub.dev/packages/flutter_launcher_icons
  # flutter_native_splash: ^2.2.17 #生成闪屏页 https://pub.dev/packages/flutter_native_splash
  url_launcher: ^6.1.8 #访问链接 https://pub.dev/packages/url_launcher
  path_provider: ^2.0.12 #路径查询 https://pub.dev/packages/path_provider
  cached_network_image: ^3.2.3 #缓存图片 https://pub.dev/packages/cached_network_image
  csv: ^5.0.1 #读取CSV https://pub.dev/packages/csv
  animate_do: ^3.0.2 #动画 https://pub.dev/packages/animate_do
  dio: ^5.0.0 #网络请求 https://pub.dev/packages/dio
  flutter_progress_hud: ^2.0.2 #屏幕加载 https://pub.dev/packages/flutter_progress_hud
  flutter_app_update: ^2.0.2 #下载apk https://pub.dev/packages/flutter_app_update
  flutter_local_notifications: ^13.0.0 #本地通知 https://pub.dev/packages/flutter_local_notifications 
  flutter_background: ^1.2.0 #后台运行 https://pub.dev/packages/flutter_background
  mobcommonlib: ^1.1.4 #推送依赖
  mobpush_plugin: ^1.2.4 #推送
  # rive: ^0.9.1 #动画

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  fonts:
    - family: YuGothic
      fonts:
        - asset: fonts/YuGothic.ttf

  assets:
    - assets/
    - assets/live2d/
    - assets/images/
    - assets/music/
    - assets/词典/
    - assets/chapter/
    - assets/icon/
    - assets/story/第一章.csv
    - assets/story/第二章.csv
    - assets/story/第三章.csv
    - assets/story/第四章.csv
    - assets/story/第五章.csv
    - assets/story/第六章.csv
    - assets/story/番外一.csv
    - assets/story/番外二.csv
    - assets/story/番外三.csv

